server:
  port: 8881
#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zhengcq.datasercher.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.80.129:3306/mytest
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver